tags:
    name: User Signup and Login Section
components:
  schemas:
    UserSchema:
      type: object
      properties:
        user_name:
          type: string
          example: Apurv
        first_name :
           type : string
           example: Apurv
        last_name:
          type: string
          example : Dubey
        email : 
          type : string 
          example : apurv@gmail.com 
        bio :
          type : string 
          example : software Trainee
        profile_pic :
          type : string
          example : profile_pic_url
        password:
          type: string 
      required:  
          username 
          email
          password
      
    UserLogin:
      type: object
      properties:
        user_name:
          type: string
        password:
          type: string
      required:
        - email
        - password


paths:
  /api/signup:
    post:
      summary: This API is used to Signup new user in Instagram.
      tags: [User Signup and Login Section]
      description: User can Signup by filling the entries.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserSchema'
      responses:
        '201':
          description: Created.
        '406':
          description: Value not accepted.
        '500':
          description: Inernal server error.          
  /api/login:
    post:
      summary: This API is used to Logged In in Instagram.
      tags: [User Signup and Login Section]
      description: User can login by filling the entries.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
      responses:
        '200':
          description : Created
        '406':
          description : Value not accepted
        '500' : 
          description : Internal server error
        
          
    # /post:
    #   summary: This API is used to Logged In in Instagram.
    #   tags: [User Signup and Login Section]
    #   description: User can login by filling the entries.
    #   requestBody:
    #     required: true
    #     content:
    #       application/json:
    #         schema:
    #           $ref: '#/controllers/Models/PostSchema'
    #   responses:
    #     '200':
    #       description: Authorized.
    #     '401':
    #       description: Unauthorized Response.
    #     '500':
    #       description: Inernal server error.